dist: trusty
sudo: required
language: c

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install doxygen

script:
  - make init
  - make test
  - make clean
